channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - bumpversion
  - dataclasses
  - colorama
  - flit
  - h5py
  - idna
  - importlib_resources
  - ipython
  - matplotlib
  - mkdocs
  - mypy
  - numpy
  - pandas
  - pint>=0.20
  - pycurl
  - pytest
  - pytest-cov
  - pytoml
  - scipy
  - statsmodels
